# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Linear combinations of submatrices of an array
#' 
#' Computes a matrix of expected values based on an array X of predictors and a
#' vector beta of regression coefficients.
#' 
#' 
#' @usage Xbeta_cpp(X, beta)
#' @param X an n by n by p array
#' @param beta a p by 1 vector
#' @return An n by n matrix
#' @author Peter Hoff, Shahryar Minhas
#' @export Xbeta_cpp
Xbeta_cpp <- function(X, beta) {
    .Call('amen_Xbeta_cpp', PACKAGE = 'amen', X, beta)
}

