# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gibbs sampling of additive row and column effects and regression coefficient
#' with independent replicate relational data
#' 
#' Simulates from the joint full conditional distribution of (a,b,beta),
#' assuming same additive row and column effects and regression coefficient
#' across replicates. 
#' 
#' 
#' @usage rbeta_ab_rep_cpp(Z.T,Sab,rho,X.T,s2=1)
#' @param Z.T n x n x T array, with the third dimension for replicates.
#' Each slice of the array is a (latent) normal relational matrix, with
#' multiplicative effects subtracted out
#' @param XrCube n x p x T row covariate array generated within ame_repL fn
#' @param XcCube n x p x T column covariate array generated within ame_repL fn
#' @param mXCube n^2 x p x T design array generated within ame_repL fn
#' @param mXtCube n^2 x p x T transposed design array generated within ame_repL fn
#' @param xxCube p x p x T regression sum of squares array generated within ame_repl fn
#' @param xxTCube p x p x T transposed regression sum of squares array generated 
#' within ame_repl fn
#' @param iSe2 variance matrix
#' @param Sabs row and column covariance
#' @param k dimensions for row and column random effects
#' @param G eigenvalue calcs from Sab
#' @param e n x k gaussian error matrix
#' @param colE column sums of e
#' @return \item{beta}{regression coefficients} \item{a}{additive row effects}
#' \item{b}{additive column effects}
#' @author Peter Hoff, Yanjun He, Shahryar Minhas
#' @export rbeta_ab_rep_fc_cpp
rbeta_ab_rep_fc_cpp <- function(zCube, XrCube, XcCube, mXCube, mXtCube, xxCube, xxTCube, iSe2, Sabs, k, G, e, colE) {
    .Call('amen_rbeta_ab_rep_fc_cpp', PACKAGE = 'amen', zCube, XrCube, XcCube, mXCube, mXtCube, xxCube, xxTCube, iSe2, Sabs, k, G, e, colE)
}

#' Linear combinations of submatrices of an array
#' 
#' Computes a matrix of expected values based on an array X of predictors and a
#' vector beta of regression coefficients.
#' 
#' 
#' @usage Xbeta_cpp(X, beta)
#' @param X an n by n by p array
#' @param beta a p by 1 vector
#' @return An n by n matrix
#' @author Peter Hoff, Shahryar Minhas
#' @export Xbeta_cpp
Xbeta_cpp <- function(X, beta) {
    .Call('amen_Xbeta_cpp', PACKAGE = 'amen', X, beta)
}

